version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      # Prefix all commit messages with "pip"
      prefix: "pip"
    # Specify labels for pip pull requests
    labels:
      - "pip"
      - "dependencies"

