[tool.poetry]
name = "py-documentation-generator"
version = "0.1.0"
description = "Generating documentation for python projects"
authors = ["thoroc <thomas.a.roche@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
loguru = "^0.6.0"
GitPython = "^3.1.27"
pandas = "^1.4.3"
tabulate = "^0.8.10"
astor = "^0.8.1"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
autopep8 = "^1.6.0"
isort = "^5.10.1"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
